### ISSUE TITLE
OpenKM alternative open source solution

### ISSUE THREAD

**Issue by MartinX3** [MartinX3/MartinX3#2]
- https://github.com/paperless-ngx/paperless-ngx
- https://sourceforge.net/p/seeddms/code/ci/master/tree/
- https://github.com/jonashellmann/everydocs-core

OpenKM turned closed source with v7 and probably v6.4
https://github.com/openkm/document-management-system/issues/314
https://github.com/openkm/document-management-system

Sadly they don't communicate it and removed the referring issue ticket.

Reference to existing bug tickets not falling under their censorship
https://github.com/openkm/document-management-system/issues/315
https://github.com/openkm/document-management-system/issues/313
https://github.com/openkm/document-management-system/issues/311
https://github.com/openkm/document-management-system/issues/306
https://github.com/openkm/document-management-system/issues/294
https://github.com/openkm/document-management-system/issues/285
https://github.com/openkm/document-management-system/issues/271
https://github.com/openkm/document-management-system/issues/270
https://github.com/openkm/document-management-system/issues/261
https://github.com/openkm/document-management-system/issues/259 
https://github.com/openkm/document-management-system/issues/243
https://github.com/openkm/document-management-system/issues/225 
https://github.com/openkm/document-management-system/issues/219 
https://github.com/openkm/document-management-system/issues/208
https://github.com/openkm/document-management-system/issues/318
https://github.com/openkm/document-management-system/issues/320
https://github.com/openkm/document-management-system/issues/323
https://github.com/openkm/document-management-system/issues/325

**Comment by monkiki** [comment]
I'm sorry, but that is not true and you are deliberately harming the project just to try to benefit the other. It is very sad.

**Comment by MartinX3** [comment]
Then restore the deleted issue ticket https://github.com/openkm/document-management-system/issues/314 and the other questions about it, you removed.

And link the source code of
- 6.4
  https://docs.openkm.com/kcenter/view/okm-6.4/
- 7.1
  https://docs.openkm.com/kcenter/view/okm-7.1/

Until then the current fact is that the latest GPL version is v6.3.
And that you release OpenKM since 6.4 under the license closed source `EULA - OpenKM End User License Agreement`

Also 6.3 only barely gets updates. 7.1 is maintained.

**Comment by monkiki** [comment]
I don't really know why this issue was deleted.

OpenKM 6.4 and 7.1 are not Open Source and never were Open Source.

About OpenKM 6.3 maintenance, we almost no receive contributions but you are welcome to submit improvements.
